=== salomalo/Step_Academy/XML/XML_Step_Lessons/XML_3/sources/task/Task.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:simpleType name="StatusType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="failed"/>
			<xs:enumeration value="succeeded"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="DateType">
		<xs:annotation>
			<xs:documentation>
				Date format for Ukraine. Using dot as seperator.
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-9][0-9]?\.[0-9][0-9]?\.[0-9][0-9][0-9][0-9]"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="UserNameType">
		<xs:annotation>
			<xs:documentation>String type that contains two words starting with uppercase letter.
</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:maxLength value="32"/>
			<xs:pattern value="[A-Z][a-z]* [A-Z][a-z]*"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="PriorityType">
		<xs:annotation>
			<xs:documentation>
				One of: low, normal, high
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="low"/>
			<xs:enumeration value="normal"/>
			<xs:enumeration value="high"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="Report">
		<xs:annotation>
			<xs:documentation>Report text, userName and date</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="userName" type="UserNameType" use="required"/>
					<xs:attribute name="date" type="DateType" use="optional"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="Results">
		<xs:complexType>
			<xs:sequence>
				<xs:choice maxOccurs="unbounded">
					<xs:element ref="Report"/>
					<xs:element name="Document">
						<xs:complexType>
							<xs:attribute name="file" type="xs:string" use="required"/>
						</xs:complexType>
					</xs:element>
				</xs:choice>
			</xs:sequence>
			<xs:attribute name="overallStatus" type="StatusType" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Receivers">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="User" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="name" type="UserNameType" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Reports">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Report" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Task">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Receivers"/>
				<xs:element name="Description" type="xs:string"/>
				<xs:element ref="Reports" minOccurs="0"/>
				<xs:element ref="Results" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="submitDate" type="DateType" use="required"/>
			<xs:attribute name="submiter" type="UserNameType" use="required"/>
			<xs:attribute name="priority" type="PriorityType" use="optional" default="normal"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== salomalo/Step_Academy/XML/XML_Step_Lessons/XML_3/sources/task/Task01.xml
<?xml version="1.0" encoding="UTF-8"?>
<Task submitDate="10.07.2006" submiter="John Smith" priority="high" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Task.xsd">
	<Receivers>
		<User name="Antony Smith"/>
		<User name="William Blacke"/>
		<User name="Gordon Freeman"/>
	</Receivers>
	<Description>
		Research healing posibilities of russian vodka
	</Description>
	<Reports>
		<Report userName="Antony Smith" date="11.07.2006">
			Research started...
		</Report>
		<Report userName="William Blacke" date="12.07.2006">
			Gathering theoretical information about research subject
		</Report>
		<Report userName="Gordon Freeman" date="13.07.2006">
			Signed as a volunteer for testing
		</Report>
		<Report userName="Gordon Freeman" date="13.07.2006">
			First day. Little head aiche.
		</Report>
		<Report userName="Gordon Freeman" date="13.07.2006">
			Second day. Can't remember anything about yesterday.
		</Report>
		<Report userName="Gordon Freeman" date="13.07.2006">
			Second day. Found plasma gun. Moved to level 4. 
			Killed evil monsters in the office.
		</Report>
		<Report userName="John Smith">
			Closing project due lack of funds.
		</Report>
	</Reports>
	<Results overallStatus="failed">
		<Document file="results.xls"/>
		<Report userName="Antony Smith" date="15.07.2006">
			Not enough materials to test with.
		</Report>
		<Document file="report.doc"/>
		<Document file="alcohol_measure.cpp"/>
	</Results>
</Task>
