=== salomalo/Step_Academy/XML/XML_Step_Lessons/XML_3/sources/notebook/notebook.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="notebook">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="person" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="name"/>
							<xs:element name="age">
								<xs:complexType>
									<xs:attribute name="value" type="xs:int" use="required"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="phone">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="color" type="xs:string" use="optional"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="city">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="type" type="xs:string" use="required"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== salomalo/Step_Academy/XML/XML_Step_Lessons/XML_3/sources/notebook/notebook.xml
<?xml version="1.0" encoding="UTF-8"?>
<notebook xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="notebook.xsd">
	<person>
		<name>Olga</name>
		<age value="12" />
		<phone color="#ff0000">8(097)22-22-22</phone>
		<city type="смт">Zmerynka</city>
	</person>
	<person>
		<name>Vovan</name>
		<age value="45" />
		<phone color="#ffff00">8(097)111-22-22</phone>
		<city type="місто">Rivne</city>
	</person>
</notebook>
