=== salomalo/Step_Academy/XML/XML_Step_Lessons/XML_2/source/version_1/notebook.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT notebook (person)+>
<!ELEMENT person ANY>
<!ELEMENT fullname EMPTY>  
<!ELEMENT phone (#PCDATA)> 
<!ELEMENT city (#PCDATA)>      
<!ELEMENT text (#PCDATA)>

=== salomalo/Step_Academy/XML/XML_Step_Lessons/XML_2/source/version_1/notebook.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE notebook SYSTEM "notebook.dtd">
<notebook>
	<person>
		<fullname/>
		<phone>22-22-22</phone>
		<city>Zmerinka</city>
	</person>
	<person>
		<fullname />
		<phone>333-33-33</phone>
		<city>Kyev</city>
	</person>	
</notebook>
